--- # Install applications required for awsCLI and boto

# Update the cache for apt

- name: update apt cache
  action: apt update_cache=yes

# Install python-pip

- name: install python-pip
  apt: name={{ item }} state=present
  with_items:
   - python-pip

# Install pip packages - boto, awscli and boto3

- name: Install pip packages
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - { name: 'boto', version: '2.45.0' }
    - { name: 'awscli', version: '1.11.44' }
    - { name: 'boto3', version: '1.4.0' }
